
use master
drop database XMBE

CREATE DATABASE XMBE;

USE XMBE;

CREATE TABLE [User]
(
	[id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [name] NVARCHAR(100) NOT NULL,
    [username] NVARCHAR(50) NOT NULL UNIQUE,
    [password] NVARCHAR(255) NOT NULL,
    [role] NVARCHAR(50) NOT NULL
)
INSERT INTO [User] ([id], [name], [username], [password], [role])
VALUES 
    (NEWID(), 'Son Tung', 'admin', '123', 'Admin'),
    (NEWID(), 'Phuong Hang', 'manager', '123', 'Manager'),
    (NEWID(), 'Truong My Lan', 'admin2', '12345', 'Admin'),
    (NEWID(), 'Le Roi', 'manager2', '12345', 'Manager');

CREATE TABLE DANHMUC
(
	MADM INT PRIMARY KEY,
	TENDM NVARCHAR(50) NOT NULL
)
CREATE TABLE SANPHAM
(
	MASP INT PRIMARY KEY,
	MADM INT,
	TENSP NVARCHAR(MAX) NOT NULL,
	GiaBan money,
	MOTA TEXT,
	SoLuongCon int,
	XuatXu char(50),
	CONSTRAINT FK_DM_FR_SP FOREIGN KEY(MADM) REFERENCES DANHMUC
)
CREATE TABLE CHUYEN
(
	MACHUYEN INT PRIMARY KEY,
	SOCN INT,
	NHIEMVU NVARCHAR(50),
	VITRI CHAR(2)
)
CREATE TABLE DONHANG
(
	MADON INT PRIMARY KEY,
	NGAYDAT DATE,
	SOLUONG INT,
	MASP INT,
	CONSTRAINT FK_SP_FR_DH FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)
CREATE TABLE CONGVIEC
(
	MACV INT PRIMARY KEY,
	MACHUYEN INT,
	MADH INT,
	SOLUONG INT,
	TENCV NVARCHAR(50),
	THOIGIAN NCHAR(10),
	CONSTRAINT FK_DH_FR_CV FOREIGN KEY (MADH) REFERENCES DONHANG(MADON)
   ,CONSTRAINT FK_CHUYEN_FR_CV FOREIGN KEY (MACHUYEN) REFERENCES CHUYEN(MACHUYEN)
)